{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "controlled-job.labels" . | nindent 4 }}
    {{- with .Values.namespace.extraLabels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
{{- end -}}
