# permissions for end users to edit controlledjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlledjob-editor-role
rules:
- apiGroups:
  - batch.gresearch.co.uk
  resources:
  - controlledjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.gresearch.co.uk
  resources:
  - controlledjobs/status
  verbs:
  - get
