# permissions for end users to view controlledjobs and for the operator to watch and view controlledjobs at the cluster scope
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controlledjob-viewer-role
rules:
- apiGroups:
  - batch.gresearch.co.uk
  resources:
  - controlledjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.gresearch.co.uk
  resources:
  - controlledjobs/status
  verbs:
  - get
