apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-operator" (include "controlled-job.fullname" .) }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "controlled-job.labels" . | nindent 4 }}
    {{- with .Values.deployment.extraLabels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels: {{- include "controlled-job.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "controlled-job.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: controlled-job-operator
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        imagePullPolicy: IfNotPresent
        command: 
          - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:5000
          - --metrics-bind-address=:8080
          - --enable-auto-recreate-jobs-on-spec-change=true
          {{- with .Values.deployment.jobAdmissionWebhookUrl }}
          - --job-admission-webhook-url={{ . }}
          {{- end }}
        ports:
          - containerPort: 8080
            name: metrics
            protocol: TCP
        terminationMessagePolicy: "FallbackToLogsOnError"
        {{- with .Values.deployment.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext: 
          runAsUser: 1000
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 -}}
        {{- end }}
        {{- with .Values.deployment.extraVolumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 10 -}}
        {{- end }}
        {{- with .Values.deployment.extraEnv }}
        env:
          {{- toYaml . | nindent 10 -}}
        {{- end }}
      {{- with .Values.deployment.extraVolumes }}
      volumes:        
        {{- toYaml . | nindent 8 -}}
      {{- end }}