apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlled-job.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "controlled-job.labels" . | nindent 4 }}
    {{- with .Values.service.extraLabels }}
      {{- toYaml . | nindent 4 -}}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "controlled-job.selectorLabels" . | nindent 4 }}